// This file is autogenerated by CMake. Do not edit.

#include <QtCore/qtsymbolmacros.h>
#include <QtQml/qqmlextensionplugin.h>




$<$<BOOL:qml_register_types_MainUi_Common>:QT_DECLARE_EXTERN_SYMBOL_VOID($<JOIN:qml_register_types_MainUi_Common,)
QT_DECLARE_EXTERN_SYMBOL_VOID(>)>

class MainUi_CommonPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MainUi_CommonPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {

$<$<BOOL:qml_register_types_MainUi_Common>:QT_KEEP_SYMBOL($<JOIN:qml_register_types_MainUi_Common,)
QT_KEEP_SYMBOL(>)>
    }
};



#include "commonplugin_MainUi_CommonPlugin.moc"
